### ISSUE TITLE
Configuration path does not exist

### ISSUE THREAD

**Issue by jsatyam7** [sodadata/soda-github-action#12]
I have added this code to my GitHub actions pipeline -
      - name: Perform Soda Scan
        uses: sodadata/soda-github-action@v1.0.2
        env:
          SODA_CLOUD_API_KEY: SODA_CLOUD_API_KEY
          SODA_CLOUD_API_SECRET: SODA_CLOUD_API_SECRET
          SNOWFLAKE_USERNAME: Username
          SNOWFLAKE_PASSWORD: Password
        with:
          soda_library_version: v1.0.4
          data_source: snowflake_soda_poc
          configuration: ${{ github.workspace }}/soda/configuration.yaml
          checks: ${{ github.workspace }}/soda/checks.yaml

It is adding /tmp/workspace/  as a prefix to my configuration path due to this i'm getting this error - 
Configuration path '/tmp/workspace//home/runner/work/dbt_training/dbt_training/soda/configuration.yaml' does not exist
[17:08:14] Path "/tmp/workspace//home/runner/work/dbt_training/dbt_training/soda/checks.yaml" does not exist

Any help is appreciated...

**Comment by gregkaczan** [comment]
Hey. Try not using `github.workspace` var in Your path. Simply define the path to the file relative to the root of the repo, so just `./soda/configuration.yaml` (assuming soda is a root folder in the repo).
Same for checks file.

Ping me again if it helped or not.

**Comment by jsatyam7** [comment]
Hi gregkaczan, thanks for the response. I tried removing github.workspace var in my path but still i'm getting the error.
[02:39:38] Configuration path '/tmp/workspace/./soda/configuration.yaml' does not exist
[02:39:38] Path "/tmp/workspace/./soda/checks.yaml" does not exist.

This is my project structure, am I missing any things?

<img width="235" alt="Screenshot 2023-11-24 at 8 13 37 AM" src="https://github.com/sodadata/soda-github-action/assets/91525712/85df02c5-8aea-43c6-8075-263cb1fadbc6">

**Comment by jsatyam7** [comment]
THis is the issue which i'm facing...
Run sodadata/soda-github-action@v1.0.2
Run [[ "v1.0.4" ]] || { echo -e "\033[31;1;4m[Soda Library Github Action] Input: 'soda_library_version' is required\033[0m" ; exit 1; }
Run docker build \
#0 building with "default" instance using docker driver

#1 [internal] load .dockerignore
#1 transferring context: 2B done
#1 DONE 0.0s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 332B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/sodadata/soda-library:v1.0.4
#3 ...

#4 [auth] sodadata/soda-library:pull token for registry-1.docker.io
#4 DONE 0.0s

#3 [internal] load metadata for docker.io/sodadata/soda-library:v1.0.4
#3 DONE 1.0s

#5 [internal] load build context
#5 transferring context: 541B done
#5 DONE 0.0s

#6 [1/3] FROM docker.io/sodadata/soda-library:v1.0.4@sha256:432e0ff11033d1deed64c3728eecc381031af6b085db0c77f77fdd356a3da7ca
#6 resolve docker.io/sodadata/soda-library:v1.0.4@sha256:432e0ff11033d1deed64c3728eecc381031af6b085db0c77f77fdd356a3da7ca done
#6 sha256:a032e966b886f1bc796b64b8992ada842ad5ac1a0f11f6109746c6dba24db1a1 0B / 206.74MB 0.1s
#6 sha256:798911fcd3a63a1c0e71388e220c8ea903c7b097445240a35f783e45f9b61e19 0B / 2.24MB 0.1s
#6 sha256:a516fe209ec158a93e313c16c338c1f40d895cdf11519f9403f701a1085ff2f3 6.49kB / 6.49kB done
#6 sha256:3153aa388d026c26a2235e1ed0163e350e451f41a8a313e1804d7e1afb857ab4 13.63MB / 29.53MB 0.2s
#6 sha256:432e0ff11033d1deed64c3728eecc381031af6b085db0c77f77fdd356a3da7ca 2.48kB / 2.48kB done
#6 sha256:a032e966b886f1bc796b64b8992ada842ad5ac1a0f11f6109746c6dba24db1a1 18.87MB / 206.74MB 0.4s
#6 sha256:798911fcd3a63a1c0e71388e220c8ea903c7b097445240a35f783e45f9b61e19 2.24MB / 2.24MB 0.3s done
#6 sha256:3153aa388d026c26a2235e1ed0163e350e451f41a8a313e1804d7e1afb857ab4 26.21MB / 29.53MB 0.4s
#6 sha256:90267fdbb62aff8ecce8f553b971a35d9dd77ab0c8647e35566fd93895647fb5 0B / 26.61MB 0.4s
#6 sha256:3153aa388d026c26a2235e1ed0163e350e451f41a8a313e1804d7e1afb857ab4 29.53MB / 29.53MB 0.5s done
#6 sha256:90267fdbb62aff8ecce8f553b971a35d9dd77ab0c8647e35566fd93895647fb5 13.63MB / 26.61MB 0.5s
#6 sha256:7331[284](https://github.com/jsatyam7/dbt_training/actions/runs/6977202785/job/18986688527?pr=2#step:9:287)d05ce1b245784676d279b3fc56a2f590bcf06b470d78de5e7a5a515d7 0B / 712B 0.5s
#6 extracting sha256:3153aa388d026c26a2235e1ed0163e350e451f41a8a313e1804d7e1afb857ab4
#6 sha256:a032e966b886f1bc796b64b8992ada842ad5ac1a0f11f6109746c6dba24db1a1 45.09MB / 206.74MB 0.7s
#6 sha256:90267fdbb62aff8ecce8f553b971a35d9dd77ab0c8647e35566fd93895647fb5 26.61MB / 26.61MB 0.7s done
#6 sha256:7331284d05ce1b245784676d279b3fc56a2f590bcf06b470d78de5e7a5a515d7 712B / 712B 0.7s done
#6 sha256:8a050e340e63c656fd717b234cf56648c49a9494e9523bfd5b8a889e954483d5 0B / 10.60MB 0.7s
#6 sha256:74c32a049964faf1d77a3fb312d38066b6e5001c03081e6d6852c528c176216c 0B / 93B 0.7s
#6 sha256:a032e966b886f1bc796b64b8992ada842ad5ac1a0f11f6109746c6dba24db1a1 65.01MB / 206.74MB 0.9s
#6 sha256:74c32a049964faf1d77a3fb312d38066b6e5001c03081e6d6852c528c176216c 93B / 93B 0.8s done
#6 sha256:07c7c5b3299b7ccc8c58f4afe7b8a6ccd71ea107eddfb8218e991b8249c26456 0B / 27.50kB 0.9s
#6 sha256:a032e966b886f1bc796b64b8992ada842ad5ac1a0f11f6109746c6dba24db1a1 79.22MB / 206.74MB 1.0s
#6 sha256:07c7c5b3299b7ccc8c58f4afe7b8a6ccd71ea107eddfb8218e991b8249c26456 27.50kB / 27.50kB 0.9s done
#6 sha256:931d46396003311331f995cdb1447200193d22387c3697eaee6d568969964ab5 0B / 710.07kB 1.0s
#6 sha256:a032e966b886f1bc796b64b8992ada842ad5ac1a0f11f6109746c6dba24db1a1 96.47MB / 206.74MB 1.1s
#6 sha256:8a050e340e63c656fd717b234cf56648c49a9494e9523bfd5b8a889e954483d5 1.05MB / 10.60MB 1.1s
#6 sha256:931d46396003311331f995cdb1447200193d22387c3697eaee6d568969964ab5 710.07kB / 710.07kB 1.1s done
#6 sha256:9708583fc2e6273901404fa80f1baa981f31e8c85681ebfaac24e3f593a96211 0B / 665.20MB 1.1s
#6 sha256:a032e966b886f1bc796b64b8992ada842ad5ac1a0f11f6109746c6dba24db1a1 109.05MB / 206.74MB 1.2s
#6 sha256:8a050e340e63c656fd717b234cf56648c49a9494e9523bfd5b8a889e954483d5 5.24MB / 10.60MB 1.2s
#6 sha256:a032e966b886f1bc796b64b8992ada842ad5ac1a0f11f6109746c6dba24db1a1 140.51MB / 206.74MB 1.4s
#6 sha256:8a050e340e63c656fd717b234cf56648c49a9494e9523bfd5b8a889e954483d5 10.60MB / 10.60MB 1.3s done
#6 sha256:1fbe1ec83f7ff84[285](https://github.com/jsatyam7/dbt_training/actions/runs/6977202785/job/18986688527?pr=2#step:9:288)15785a00a6f05ac6a57d06eabe59cb79028d2d1fd28d21 0B / 209.65kB 1.4s
#6 sha256:a032e966b886f1bc796b64b8992ada842ad5ac1a0f11f6109746c6dba24db1a1 154.14MB / 206.74MB 1.5s
#6 sha256:1fbe1ec83f7ff8428515785a00a6f05ac6a57d06eabe59cb79028d2d1fd28d21 209.65kB / 209.65kB 1.4s done
#6 sha256:a032e966b886f1bc796b64b8992ada842ad5ac1a0f11f6109746c6dba24db1a1 167.77MB / 206.74MB 1.6s
#6 sha256:a032e966b886f1bc796b64b8992ada842ad5ac1a0f11f6109746c6dba24db1a1 180.36MB / 206.74MB 1.7s
#6 sha256:a032e966b886f1bc796b64b8992ada842ad5ac1a0f11f6109746c6dba24db1a1 206.74MB / 206.74MB 1.9s
#6 sha256:9708583fc2e6273901404fa80f1baa981f31e8c85681ebfaac24e3f593a96211 37.75MB / 665.20MB 1.9s
#6 sha256:9708583fc2e6273901404fa80f1baa981f31e8c85681ebfaac24e3f593a96211 92.27MB / 665.20MB 2.3s
#6 extracting sha256:3153aa388d026c26a2235e1ed0163e350e451f41a8a313e1804d7e1afb857ab4 1.8s done
#6 sha256:a032e966b886f1bc796b64b8992ada842ad5ac1a0f11f6109746c6dba24db1a1 206.74MB / 206.74MB 2.6s done
#6 sha256:9708583fc2e6273901404fa80f1baa981f31e8c85681ebfaac24e3f593a96211 140.51MB / 665.20MB 2.7s
#6 extracting sha256:a032e966b886f1bc796b64b8992ada842ad5ac1a0f11f6109746c6dba24db1a1
#6 sha256:9708583fc2e6273901404fa80f1baa981f31e8c85681ebfaac24e3f593a96211 183.50MB / 665.20MB 3.0s
#6 sha256:9708583fc2e6273901404fa80f1baa981f31e8c85681ebfaac24e3f593a96211 220.20MB / 665.20MB 3.3s
#6 sha256:9708583fc2e6273901404fa80f1baa981f31e8c85681ebfaac24e3f593a96211 254.80MB / 665.20MB 3.6s
#6 sha256:9708583fc2e6273901404fa80f1baa981f31e8c85681ebfaac24e3f593a96211 [293](https://github.com/jsatyam7/dbt_training/actions/runs/6977202785/job/18986688527?pr=2#step:9:296).60MB / 665.20MB 3.9s
#6 sha256:9708583fc2e6273901404fa80f1baa981f31e8c85681ebfaac24e3f593a96211 353.37MB / 665.20MB 4.3s
#6 sha256:9708583fc2e6273901404fa80f1baa981f31e8c85681ebfaac24e3f593a96211 396.36MB / 665.20MB 4.6s
#6 sha256:9708583fc2e6273901404fa80f1baa981f31e8c85681ebfaac24e3f593a96211 455.08MB / 665.20MB 5.1s
#6 sha256:9708583fc2e6273901404fa80f1baa981f31e8c85681ebfaac24e3f593a96211 492.97MB / 665.20MB 5.4s
#6 sha256:9708583fc2e6273901404fa80f1baa981f31e8c85681ebfaac24e3f593a96211 530.58MB / 665.20MB 5.7s
#6 sha256:9708583fc2e6273901404fa80f1baa981f31e8c85681ebfaac24e3f593a96211 574.62MB / 665.20MB 6.0s
#6 sha256:9708583fc2e6273901404fa80f1baa981f31e8c85681ebfaac24e3f593a96211 613.42MB / 665.20MB 6.3s
#6 sha256:9708583fc2e6273901404fa80f1baa981f31e8c85681ebfaac24e3f593a96211 665.20MB / 665.20MB 6.7s
#6 extracting sha256:a032e966b886f1bc796b64b8992ada842ad5ac1a0f11f6109746c6dba24db1a1 5.0s
#6 sha256:9708583fc2e6273901404fa80f1baa981f31e8c85681ebfaac24e3f593a96211 665.20MB / 665.20MB 9.2s done
#6 extracting sha256:a032e966b886f1bc796b64b8992ada842ad5ac1a0f11f6109746c6dba24db1a1 8.9s done
#6 extracting sha256:798911fcd3a63a1c0e71388e220c8ea903c7b097445240a35f783e45f9b61e19 0.1s done
#6 extracting sha256:90267fdbb62aff8ecce8f553b971a35d9dd77ab0c8647e35566fd93895647fb5 0.1s
#6 extracting sha256:90267fdbb62aff8ecce8f553b971a35d9dd77ab0c8647e35566fd93895647fb5 0.5s done
#6 extracting sha256:7331284d05ce1b245784676d279b3fc56a2f590bcf06b470d78de5e7a5a515d7 done
#6 extracting sha256:8a050e340e63c656fd717b234cf56648c49a9494e9523bfd5b8a889e954483d5
#6 extracting sha256:8a050e340e63c656fd717b234cf56648c49a9494e9523bfd5b8a889e954483d5 0.6s done
#6 extracting sha256:74c32a049964faf1d77a3fb312d38066b6e5001c03081e6d6852c528c176216c done
#6 extracting sha256:07c7c5b3[299](https://github.com/jsatyam7/dbt_training/actions/runs/6977202785/job/18986688527?pr=2#step:9:302)b7ccc8c58f4afe7b8a6ccd71ea107eddfb8218e991b8249c26456 done
#6 extracting sha256:931d46396003[311](https://github.com/jsatyam7/dbt_training/actions/runs/6977202785/job/18986688527?pr=2#step:9:314)331f995cdb1447200193d22387c3697eaee6d568969964ab5 0.1s done
#6 extracting sha256:9708583fc2e6273901404fa80f1baa981f31e8c85681ebfaac24e3f593a96211
#6 extracting sha256:9708583fc2e6273901404fa80f1baa981f31e8c85681ebfaac24e3f593a96211 5.1s
#6 extracting sha256:9708583fc2e6273901404fa80f1baa981f31e8c85681ebfaac24e3f593a96211 10.1s
#6 extracting sha256:9708583fc2e6273901404fa80f1baa981f31e8c85681ebfaac24e3f593a96211 15.2s
#6 extracting sha256:9708583fc2e6273901404fa80f1baa981f31e8c85681ebfaac24e3f593a96211 19.2s done
#6 extracting sha256:1fbe1ec83f7ff8428515785a00a6f05ac6a57d06eabe59cb79028d2d1fd28d21
#6 extracting sha256:1fbe1ec83f7ff8428515785a00a6f05ac6a57d06eabe59cb79028d2d1fd28d21 0.1s done
#6 DONE 36.3s

#7 [2/3] COPY entrypoint.sh /entrypoint.sh
#7 DONE 0.0s

#8 [3/3] RUN chmod +x /entrypoint.sh
#8 DONE 0.3s

#9 exporting to image
#9 exporting layers
#9 exporting layers 2.2s done
#9 writing image sha256:afda989c8b6df871[313](https://github.com/jsatyam7/dbt_training/actions/runs/6977202785/job/18986688527?pr=2#step:9:316)6fca9d73e4ded39b31125e119ec3c4fa4789626fe9ef0 done
#9 naming to docker.io/library/soda_action_dd5d440cacad6edb982f5f0be466aafc095a4cfc done
#9 DONE 2.2s
Run env > .env_file
Run docker run \
[05:28:37] Soda Library 1.0.4
[05:28:37] Soda Core 3.0.39
[05:28:37] Configuration path '/tmp/workspace//home/runner/work/dbt_training/dbt_training/soda/configuration.yaml' does not exist
[05:28:37] Path "/tmp/workspace//home/runner/work/dbt_training/dbt_training/soda/checks.yaml" does not exist
[05:28:37] By downloading and using Soda Library, you agree to Soda's Terms & Conditions (https://go.soda.io/t&c) and Privacy Policy (https://go.soda.io/privacy). 
[05:28:37] You have not configured Soda Library to work with Soda Cloud. Add Soda Cloud API keys (https://go.soda.io/configure) to run a scan.
[05:28:37] Error occurred while executing scan.
  | Pre-scan validation failed, see logs for details.
Saving scan results to soda_scan_results_raw.json
[05:28:37] Data source 'snowflake_soda_poc' not present in the configuration. Configured data sources: 
Traceback (most recent call last):
  File "/usr/local/bin/soda", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 16[88](https://github.com/jsatyam7/dbt_training/actions/runs/6977202785/job/18986688527?pr=2#step:9:91), in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/soda/telemetry/soda_tracer.py", line 79, in wrapper
    raise e
  File "/usr/local/lib/python3.9/dist-packages/soda/telemetry/soda_tracer.py", line 72, in wrapper
    result = fn(*original_args, **original_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/soda/cli/cli.py", line 230, in scan
    sys.exit(scan.execute())
  File "/usr/local/lib/python3.9/dist-packages/soda/scan.py", line 714, in execute
    SodaCloud.build_scan_results(self, scan_metadata),
  File "/usr/local/lib/python3.9/dist-packages/soda/cloud/soda_cloud.py", line [94](https://github.com/jsatyam7/dbt_training/actions/runs/6977202785/job/18986688527?pr=2#step:9:97), in build_scan_results
    default_data_source = scan._get_or_create_data_source_scan(scan._data_source_name).data_source
AttributeError: 'NoneType' object has no attribute 'data_source'
Run echo -e "\033[36;1m-----------------------------\033[0m"

**Comment by gregkaczan** [comment]
Still don't understand how the path gets constructed as 
`/tmp/workspace//home/runner/work/dbt_training/dbt_training/soda/configuration.yaml`
and not as 
`/tmp/workspace/./soda/configuration.yaml`

What is the contents of `soda` folder?
Are You perhaps running this on local runner?

Please provide action configuration in Your pipeline. 

As this is not enough to figure out why the path is not found.
All the repo files, including `soda` folder are being mounted under the `/tmp/workspace` so it should be accessible there normally.

**Comment by jsatyam7** [comment]
No we are getting these error - /tmp/workspace/./soda/configuration.yaml
<img width="977" alt="Screenshot 2023-11-24 at 3 27 10 PM" src="https://github.com/sodadata/soda-github-action/assets/91525712/9436911b-a6e6-44d7-babf-3e9344a8cfdc">

the contents of soda folder are - 
<img width="278" alt="Screenshot 2023-11-24 at 3 17 27 PM" src="https://github.com/sodadata/soda-github-action/assets/91525712/c9ed67b5-2f7f-48ac-9983-1a30c2709406">

What do you mean by this? -  "Are You perhaps running this on local runner? and Please provide action configuration in Your pipeline."

**Comment by gregkaczan** [comment]
It seems You configured the action to use `soda/configuration.yaml` but the file is actually `soda/configuration.yml`.
Notice the extension: `yaml` vs `yml`

Change config of the action in the pipeline to:
```
configuration: ./soda/configuration.yml
checks: ./soda/checks.yml
```

**Comment by jsatyam7** [comment]
Hey man!!! thanks for pointing it out. It is fixed now. Thanks for your help. Really appreciate it. :)

**Comment by gregkaczan** [comment]
Awesome, happy testing!
